# Generated by Django 5.2.6 on 2025-09-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedido', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto')),
                ('opening_time', models.TimeField(verbose_name='Horário de Abertura')),
                ('closing_time', models.TimeField(verbose_name='Horário de Fechamento')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Taxa de Entrega')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('clients', models.ManyToManyField(blank=True, related_name='restaurants', to='cliente.cliente', verbose_name='Clientes')),
                ('menu', models.ManyToManyField(blank=True, related_name='restaurants', to='produto.produto', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='Cozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number_of_chefs', models.PositiveIntegerField(default=1, verbose_name='Número de Chefs')),
                ('number_of_stations', models.PositiveIntegerField(default=1, help_text='Quantas estações de preparo estão disponíveis', verbose_name='Número de Estações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('orders_in_progress', models.ManyToManyField(blank=True, limit_choices_to={'status': '3'}, related_name='kitchen_in_progress', to='pedido.pedido', verbose_name='Pedidos em Progresso')),
                ('orders_in_queue', models.ManyToManyField(blank=True, limit_choices_to={'status': '2'}, related_name='kitchen_queue', to='pedido.pedido', verbose_name='Pedidos na Fila')),
                ('orders_ready', models.ManyToManyField(blank=True, limit_choices_to={'status': '4'}, related_name='kitchen_ready', to='pedido.pedido', verbose_name='Pedidos Prontos')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cozinha', to='restaurante.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Cozinha',
                'verbose_name_plural': 'Cozinhas',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Receita Total')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Receita do Dia')),
                ('last_reset_date', models.DateField(auto_now_add=True, verbose_name='Último Reset')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caixa', to='restaurante.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='EstacaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Estação')),
                ('tipo', models.CharField(choices=[('grill', 'Grill'), ('fryer', 'Fritadeira'), ('prep', 'Preparo'), ('drinks', 'Bebidas'), ('dessert', 'Sobremesas'), ('assembly', 'Montagem')], max_length=30, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('cozinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='restaurante.cozinha', verbose_name='Cozinha')),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido', verbose_name='Pedido Atual')),
            ],
            options={
                'verbose_name': 'Estação de Trabalho',
                'verbose_name_plural': 'Estações de Trabalho',
                'unique_together': {('cozinha', 'name')},
            },
        ),
    ]
