# Generated by Django 5.2.6 on 2025-09-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço do produto no momento do pedido', max_digits=10, verbose_name='Preço Unitário')),
                ('special_instructions', models.TextField(blank=True, help_text='Ex: sem cebola, ponto da carne, etc.', verbose_name='Instruções Especiais')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='produto.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('-1', 'Cancelado'), ('0', 'Fazendo pedido'), ('1', 'Aguardando pagamento'), ('2', 'Aguardando'), ('3', 'Preparando'), ('4', 'Pronto'), ('5', 'Sendo entregue'), ('6', 'Entregue')], default='0', max_length=2, verbose_name='Status')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Tempo Estimado de Entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('payment_method', models.CharField(choices=[('saldo', 'Saldo da Conta'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('pix', 'PIX')], default='saldo', max_length=20, verbose_name='Método de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cliente.cliente', verbose_name='Cliente')),
                ('items', models.ManyToManyField(related_name='pedidos', through='pedido.ItemPedido', to='produto.produto', verbose_name='Itens')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Pedido'),
        ),
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status_anterior', models.CharField(choices=[('-1', 'Cancelado'), ('0', 'Fazendo pedido'), ('1', 'Aguardando pagamento'), ('2', 'Aguardando'), ('3', 'Preparando'), ('4', 'Pronto'), ('5', 'Sendo entregue'), ('6', 'Entregue')], max_length=2, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('-1', 'Cancelado'), ('0', 'Fazendo pedido'), ('1', 'Aguardando pagamento'), ('2', 'Aguardando'), ('3', 'Preparando'), ('4', 'Pronto'), ('5', 'Sendo entregue'), ('6', 'Entregue')], max_length=2, verbose_name='Status Novo')),
                ('usuario', models.CharField(blank=True, help_text='Usuário que fez a alteração', max_length=100, verbose_name='Usuário')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Histórico do Pedido',
                'verbose_name_plural': 'Histórico dos Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto')},
        ),
    ]
