# Generated by Django 5.2.5 on 2025-09-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
        ),
        migrations.CreateModel(
            name='RestricaoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Restrição Alimentar',
                'verbose_name_plural': 'Restrições Alimentares',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('calories', models.PositiveIntegerField(verbose_name='Calorias')),
                ('time_to_prepare', models.PositiveIntegerField(default=0, help_text='Tempo em minutos', verbose_name='Tempo de Preparo')),
                ('is_ingredient', models.BooleanField(default=False, help_text='Marque se este alimento pode ser usado como ingrediente em outros.', verbose_name='É um ingrediente?')),
                ('additional_ingredients', models.ManyToManyField(blank=True, limit_choices_to={'is_ingredient': True}, to='produto.alimento', verbose_name='Ingredientes Adicionais')),
                ('alimentary_restrictions', models.ManyToManyField(blank=True, to='produto.restricaoalimentar', verbose_name='Restrições Alimentares')),
            ],
            bases=('produto.produto',),
        ),
    ]
