# Generated by Django 5.2.5 on 2025-09-18 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('items', models.ManyToManyField(related_name='member_of_combos', to='produto.produto', verbose_name='Itens do Combo')),
            ],
            bases=('produto.produto',),
        ),
    ]
