# Generated by Django 5.2.6 on 2025-09-23 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('alimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.alimento')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Volume (ml)')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='É alcoólica?')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
            bases=('produto.alimento',),
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Receita Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('alimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.alimento')),
                ('persons_served', models.PositiveIntegerField(default=1, verbose_name='Pessoas servidas')),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
            },
            bases=('produto.alimento',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('alimentary_restrictions', models.ManyToManyField(blank=True, to='produto.restricaoalimentar', verbose_name='Restrições Alimentares')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('-1', 'Cancelado'), ('0', 'Fazendo pedido'), ('1', 'Aguardando pagamento'), ('2', 'Aguardando'), ('3', 'Preparando'), ('4', 'Pronto'), ('5', 'Sendo entregue'), ('6', 'Entregue')], default='0', max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='produto.cliente', verbose_name='Cliente')),
                ('items', models.ManyToManyField(through='produto.ItemPedido', to='produto.produto', verbose_name='Itens')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.pedido'),
        ),
        migrations.CreateModel(
            name='Cozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_chefs', models.PositiveIntegerField(default=1, verbose_name='Número de Chefs')),
                ('orders_in_progress', models.ManyToManyField(blank=True, related_name='kitchen_in_progress', to='produto.pedido', verbose_name='Pedidos em Progresso')),
                ('orders_in_queue', models.ManyToManyField(blank=True, related_name='kitchen_queue', to='produto.pedido', verbose_name='Pedidos na Fila')),
            ],
            options={
                'verbose_name': 'Cozinha',
                'verbose_name_plural': 'Cozinhas',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cash_register', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produto.caixa', verbose_name='Caixa')),
                ('clients', models.ManyToManyField(blank=True, related_name='restaurants', to='produto.cliente', verbose_name='Clientes')),
                ('kitchen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produto.cozinha', verbose_name='Cozinha')),
                ('menu', models.ManyToManyField(blank=True, related_name='restaurants', to='produto.produto', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto')},
        ),
    ]
