# Generated by Django 5.2.6 on 2025-09-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_temporary',
            field=models.BooleanField(default=True, help_text='Contas temporárias podem ser limpas automaticamente', verbose_name='Conta Temporária'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Pedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, help_text='Apenas para contas permanentes', max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='cliente_cli_cpf_2f614c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['is_temporary', 'last_order_date'], name='cliente_cli_is_temp_368cd2_idx'),
        ),
    ]
