# Generated by Django 5.2.5 on 2025-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_cpf_cliente_is_temporary_and_more'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='produto.restricaoalimentar', verbose_name='Restrições Alimentares'),
        ),
    ]
