# Generated by Django 5.2.6 on 2025-09-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestricaoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Restrição Alimentar',
                'verbose_name_plural': 'Restrições Alimentares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('calories', models.PositiveIntegerField(verbose_name='Calorias')),
                ('time_to_prepare', models.PositiveIntegerField(default=0, help_text='Tempo em minutos', verbose_name='Tempo de Preparo')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='Peso (gramas)')),
                ('is_ingredient', models.BooleanField(default=False, help_text='Marque se este alimento pode ser usado como ingrediente em outros.', verbose_name='É um ingrediente?')),
                ('alimentary_restrictions', models.ManyToManyField(blank=True, related_name='alimentos', to='produto.restricaoalimentar', verbose_name='Restrições Alimentares')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
            },
            bases=('produto.produto',),
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.1, help_text='Desconto aplicado sobre o valor total dos itens', max_digits=5, verbose_name='Desconto (%)')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
            bases=('produto.produto',),
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('alimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.alimento')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Volume (ml)')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='É alcoólica?')),
                ('temperature', models.CharField(choices=[('gelada', 'Gelada'), ('natural', 'Natural'), ('quente', 'Quente')], default='natural', max_length=20, verbose_name='Temperatura')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
            bases=('produto.alimento',),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('alimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.alimento')),
                ('persons_served', models.PositiveIntegerField(default=1, verbose_name='Pessoas servidas')),
                ('spice_level', models.CharField(choices=[('suave', 'Suave'), ('medio', 'Médio'), ('picante', 'Picante'), ('muito_picante', 'Muito Picante')], default='suave', max_length=20, verbose_name='Nível de Pimenta')),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
            },
            bases=('produto.alimento',),
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_memberships', to='produto.produto')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='produto.combo')),
            ],
            options={
                'verbose_name': 'Item do Combo',
                'verbose_name_plural': 'Itens do Combo',
                'unique_together': {('combo', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='items',
            field=models.ManyToManyField(related_name='member_of_combos', through='produto.ComboItem', to='produto.produto', verbose_name='Itens do Combo'),
        ),
    ]
